language: haskell
ghc:
  - 7.8
install:
  - cabal install hlint
script:
  - hlint . --ignore="Parse error"
  - cabal configure --enable-tests --enable-library-coverage && cabal build && cabal test
after_script:
  - cabal install codecov-haskell
  - codecov-haskell test-json-litobj