language: haskell
ghc:
  - 7.8
sudo: required
before_install:
  - travis_retry sudo apt-get install happy  
install:
  - cabal install hlint
script:
  - hlint . --ignore="Parse error"
  - cabal configure --enable-tests --enable-library-coverage && cabal build && cabal test --show-details=always
after_script:
  - cabal install codecov-haskell
  - codecov-haskell test-json-litobj